apiVersion: v1
kind: Pod
metadata:
  name: testclient
  namespace: default
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-kafkacat
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
